apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: c2o-workspace
  labels:
    app: c2o
    c2o.instance: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
