apiVersion: v1
kind: Service
metadata:
  name: c2o-anthropic
  labels:
    app: c2o
    c2o.instance: default
spec:
  selector:
    app: c2o
    c2o.instance: default
  ports:
  - port: 8819
    targetPort: 8819
    name: anthropic
---
apiVersion: v1
kind: Service
metadata:
  name: c2o-openai
  labels:
    app: c2o
    c2o.instance: default
spec:
  selector:
    app: c2o
    c2o.instance: default
  ports:
  - port: 8899
    targetPort: 8899
    name: openai
